---
- name: Add Jenkins-CI Repository Key
  apt_key:
    url: "http://pkg.jenkins.io/{{ ansible_os_family|lower }}/jenkins.io.key"
    state: present

- name: Add Jenkins-CI Repository
  apt_repository:
    repo: 'deb http://pkg.jenkins.io/{{ ansible_os_family|lower }} binary/'
    state: present
    update_cache: yes

- name: Install Jenkins-CI
  apt:
    name: jenkins
    state: present
    update_cache: yes
    cache_valid_time: 600
  notify:
    - Restart Jenkins

- name: Add Jenkins user to docker group
  user:
    name: jenkins
    groups: docker
  notify: Restart Jenkins
