- name: Create .aws directory if it does not exist
  file:
    path: /home/ubuntu/.aws
    state: directory
    mode: '0755'

- name: Copy AWS config file to .aws directory
  become: yes
  become_method: sudo
  template:
    src: config.j2
    dest: /home/ubuntu/.aws/config
    mode: '0600'

- name: Copy AWS credentials file to .aws directory
  become: yes
  become_method: sudo
  template:
    src: credentials.j2
    dest: /home/ubuntu/.aws/credentials
    mode: '0600'

- name: terraform init
  shell: terraform -chdir=/home/ubuntu/movie-database/Terraform/Jenkins init

- name: Update the Ansible inventory file
  shell: terraform -chdir=/home/ubuntu/movie-database/Terraform/Jenkins apply -auto-approve

- name: Update the Ansible inventory file
  shell: echo -e "jenkins ansible_user=ubuntu ansible_host=$(terraform -chdir=/home/ubuntu/movie-database/Terraform/Jenkins output -json instance_public_ip)\n\n[all:vars]\nansible_ssh_private_key_file=/home/ubuntu/.ssh/movie.pem" > /home/ubuntu/movie-database/Ansible/Hosts