---
aws_profile: terraform
aws_access_key_id: XXXXXX
aws_secret_access_key: XXXXXXXXXXXX
aws_region: us-east-1
aws_output: text

terraform_version: latest
terraform_path: "/usr/local/bin/"
terraform_pkg_url: "https://releases.hashicorp.com/terraform/{{ terraform_version_to_install }}/terraform_{{ terraform_version_to_install }}_{{ os_type }}_{{ base_arch[ansible_architecture] | default('amd64') }}.zip"
os_type: linux

base_arch:
  i386: '386'
  x86_64: 'amd64'
  amd64: 'amd64'
  aarch64: 'arm64'
  armv7l: 'arm'
  armv6l: 'arm'

base_os:
  Linux: 'Linux-Unix'
  FreeBSD: 'Linux-Unix'
  OpenBSD: 'Linux-Unix'
  Solaris: 'Linux-Unix'
  Darwin: 'Linux-Unix'
  Win32NT: 'Windows'