---
- name: Add Docker Repository Key
  apt_key:
    state: present
    url: "https://download.docker.com/linux/{{ ansible_distribution|lower }}/gpg"

- name: Add Docker Repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution|lower }} {{ ansible_distribution_release|lower }} stable"
    state: present
    update_cache: yes


- name: Install Docker
  apt:
    name: docker-ce
    state: present
    update_cache: yes
    cache_valid_time: 600
