---
- name: Setting up ansible
  hosts: localhost
  gather_facts: false
  connection: local
  become: yes

  vars_files:
    - './vars/main.yml'

  roles:
    - terraform
    - setup

- name: Setting up jenkins server
  hosts: jenkins
  become: True

  roles:
    - docker
    - jenkins
    - aws
    - terraform
